export const nepaliLocations = {
  Koshi: [
    "Biratnagar",
    "Dharan",
    "Itahari",
    "Bhadrapur",
    "Kawasaki",
    "Kakarbhitta",
    "Birtamod",
  ],
  Madesh: [
    "Janakpur",
    "Birgunj",
    "Lahan",
    "Sitauli",
    "Rajbiraj",
    "Madhubani",
    "Gadhimai",
  ],
  Bagmati: [
    "Kathmandu",
    "Lalitpur",
    "Bhaktapur",
    "Sindhupalchowk",
    "Makwanpur",
    "Dholakha",
    "Ramechhap",
  ],
  Gandaki: [
    "Pokhara",
    "Gorkha",
    "Baglung",
    "Kaski",
    "Nawalpur",
    "Parbat",
    "Lamjung",
  ],
  Lumbini: [
    "Butwal",
    "Bhairahawa",
    "Kapilvastu",
    "Rupandehi",
    "Saljhandi",
    "Tansen",
    "Syangja",
  ],
  Karnali: [
    "Surkhet",
    "Dailekh",
    "Jumla",
    "Mugu",
    "Salyan",
    "Kalaiya",
    "Dolpa",
  ],
  Sudurpashchim: [
    "Dhangadhi",
    "Mahendranagar",
    "Dadeldhura",
    "Baitadi",
    "Doti",
    "Kanchanpur",
    "Achham",
  ],
};
